dff-command-selector-ru-skill:
- group: skills
  connector:
    protocol: http
    timeout: 2.0
    url: http://dff-command-selector-ru-skill:8015/respond
  dialog_formatter: state_formatters.dp_formatters:dff_command_selector_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
