compose_override:
  env_file:
  - .env
  build:
    context: .
    dockerfile: ./annotators/asr/Dockerfile
  command: flask run -h 0.0.0.0 -p 8031
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
compose_dev:
  volumes:
  - ./annotators/asr:/src
  - ./common:/src/common
  ports:
  - 8031:8031
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8031
  - PORT=8031
