SERVICE_PORT: 8144
SERVICE_NAME: dff_fashion_stylist_prompted_skill
PROMPT_FILE: common/prompts/fashion_stylist.json
GENERATIVE_SERVICE_URL: http://transformers-lm-bloomz7b:8146/respond
GENERATIVE_SERVICE_CONFIG: default_generative_config.json
GENERATIVE_TIMEOUT: 5
N_UTTERANCES_CONTEXT: 3
