compose_override:
  env_file:
  - .env
  build:
    context: .
    dockerfile: skills/meta_script_skill/Dockerfile
  command: flask run -h 0.0.0.0 -p 8054
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
compose_dev:
  volumes:
  - ./skills/meta_script_skill:/src
  - ./common:/src/common
  ports:
  - 8054:8054
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8054
  - PORT=8054
