compose_override:
  build:
    args:
      SERVICE_PORT: 8108
      SERVICE_NAME: speech_function_classifier
    context: .
    dockerfile: annotators/speech_function_classifier/Dockerfile
  command: uvicorn server:app --host 0.0.0.0 --port 8108
  ports:
  - 8108:8108
  environment:
  - CUDA_VISIBLE_DEVICES=''
  deploy:
    mode: replicated
    replicas: 1
    resources:
      limits:
        memory: 2.5G
      reservations:
        memory: 2.5G
compose_dev:
  volumes:
  - ./annotators/speech_function_classifier:/src
  - ./common:/src/common
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8108:8108
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=lnsigo.mipt.ru:8108
  - PORT=8108
