compose_override:
  env_file:
  - .env_ru
  build:
    context: .
    dockerfile: ./skills/personal_info_skill/Dockerfile
    args:
      LANGUAGE: RU
  command: flask run -h 0.0.0.0 -p 8030
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
compose_dev:
  volumes:
  - ./skills/personal_info_skill:/src
  - ./common:/src/common
  ports:
  - 8030:8030
compose_proxy: {}
