compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8018
      SERVICE_NAME: badlisted_words
    context: annotators/BadlistedWordsDetector/
  command: flask run -h 0.0.0.0 -p 8018
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
compose_dev:
  volumes:
  - ./annotators/BadlistedWordsDetector:/src
  - ./common:/src/common
  ports:
  - 8018:8018
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8018
  - PORT=8018
