name: mint-sender
endpoints:
- send
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8172
      SERVICE_NAME: mint_sender
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./services/mint_sender/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8172 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./common:/src/common
  - ./services/mint_sender:/src
  ports:
  - 8172:8172