compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8134
      SERVICE_NAME: dff_dream_persona_prompted_skill
      PROMPT_FILE: common/prompts/dream_persona.json
      GENERATIVE_SERVICE_URL: http://transformers-lm-gptj:8130/respond
      GENERATIVE_SERVICE_CONFIG: default_generative_config.json
      GENERATIVE_TIMEOUT: 5
      N_UTTERANCES_CONTEXT: 3
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8134 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
compose_dev:
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8134:8134
compose_proxy: {}
