SERVICE_PORT: 8143
SERVICE_NAME: dff_ai_faq_prompted_skill
PROMPT_FILE: common/prompts/ai_faq.json
GENERATIVE_SERVICE_URL: http://transformers-lm-bloomz7b:8146/respond
GENERATIVE_SERVICE_CONFIG: default_generative_config.json
GENERATIVE_TIMEOUT: 10
N_UTTERANCES_CONTEXT: 3
