compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8119
      SERVICE_NAME: fact_random
    context: .
    dockerfile: ./annotators/fact_random/Dockerfile
  command: flask run -h 0.0.0.0 -p 8119
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
compose_dev:
  volumes:
  - ./annotators/fact_random:/src
  - ./common:/src/common
  ports:
  - 8119:8119
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8119
  - PORT=8119
