SERVICE_PORT: 8142
SERVICE_NAME: dff_rhodes_coaching_prompted_skill
PROMPT_FILE: common/prompts/rhodes_coaching.json
GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
GENERATIVE_SERVICE_CONFIG: openai-text-davinci-003.json
GENERATIVE_TIMEOUT: 7
N_UTTERANCES_CONTEXT: 3
ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
