compose_override:
  env_file:
  - .env
  - .env_secret
  build:
    args:
      SERVICE_PORT: 8142
      SERVICE_NAME: dff_rhodes_coaching_prompted_skill
      PROMPT_FILE: common/prompts/rhodes_coaching.json
      GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
      GENERATIVE_SERVICE_CONFIG: openai-text-davinci-003.json
      GENERATIVE_TIMEOUT: 7
      N_UTTERANCES_CONTEXT: 3
      ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8142 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
compose_dev:
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8142:8142
compose_proxy: {}
