compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8098
      SERVICE_NAME: dff_sport_skill
    context: .
    dockerfile: skills/dff_sport_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8098
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
compose_dev:
  volumes:
  - ./skills/dff_sport_skill:/src
  - ./common:/src/common
  ports:
  - 8098:8098
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8098
  - PORT=8098
