name: mint-status
endpoints:
- check
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8173
      SERVICE_NAME: mint_status
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./annotators/mint_status/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8173 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 60M
      reservations:
        memory: 60M
  volumes:
  - ./common:/src/common
  - ./annotators/mint_status:/src
  ports:
  - 8173:8173