compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8061
      SERVICE_NAME: dff_coronavirus_skill
    context: .
    dockerfile: ./skills/dff_coronavirus_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8061 --reload
  deploy:
    resources:
      limits:
        memory: 192M
      reservations:
        memory: 192M
compose_dev:
  volumes:
  - ./skills/dff_coronavirus_skill:/src
  - ./common:/src/common
  ports:
  - 8061:8061
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8061
  - PORT=8061
