SERVICE_PORT: 8138
SERVICE_NAME: dff_empathetic_marketing_prompted_skill
PROMPT_FILE: common/prompts/empathetic_marketing.json
GENERATIVE_SERVICE_URL: http://transformers-lm-gptj:8130/respond
GENERATIVE_SERVICE_CONFIG: default_generative_config.json
GENERATIVE_TIMEOUT: 5
N_UTTERANCES_CONTEXT: 3
