dff-google-api-skill:
- group: skills
  connector:
    protocol: http
    timeout: 5.0
    url: http://dff-google-api-skill:8156/respond
  dialog_formatter: state_formatters.dp_formatters:dff_prompted_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis