name: dff-embodied-skill
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8041
      SERVICE_NAME: dff_embodied_skill
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./skills/dff_embodied_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8041 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./common:/src/common
  - ./skills/dff_embodied_skill:/src
  - ~/.deeppavlov:/root/.deeppavlov
  - ~/.deeppavlov/cache:/root/.cache
  ports:
  - 8041:8041