name: embodied-status
endpoints:
- check
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8043
      SERVICE_NAME: embodied_status
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./annotators/embodied_status/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8043 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./common:/src/common
  - ./annotators/embodied_status:/src
  ports:
  - 8043:8043