name: user-knowledge-graph
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8027
      SRC_DIR: annotators/user_knowledge_graph/
      SERVICE_NAME: user_knowledge_graph
      FLASK_APP: server
    context: ./
    dockerfile: annotators/user_knowledge_graph/Dockerfile
  command: flask run -h 0.0.0.0 -p 8027
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
  volumes:
  - ./annotators/user_knowledge_graph:/src
  - ~/.deeppavlov:/root/.deeppavlov
  ports:
  - 8027:8027
proxy: null