compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8144
      SERVICE_NAME: dff_da_costa_clothes_prompted_skill
      PROMPT_FILE: common/prompts/da_costa_clothes.json
      GENERATIVE_SERVICE_URL: http://transformers-lm-bloomz7b:8146/respond
      GENERATIVE_SERVICE_CONFIG: default_generative_config.json
      GENERATIVE_TIMEOUT: 5
      N_UTTERANCES_CONTEXT: 3
    context: .
    dockerfile: ./skills/dff_template_prompted_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8144 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
compose_dev:
  volumes:
  - ./skills/dff_template_prompted_skill:/src
  - ./common:/src/common
  ports:
  - 8144:8144
compose_proxy: {}
