SERVICE_PORT: 8163
SERVICE_NAME: doc_retriever
CONFIG_PATH: ./doc_retriever_config.json
ORIGINAL_FILE_PATH: ./documents/big_apple.txt
DATASET_PATH: /data/big_apple_dataset/
CUDA_VISIBLE_DEVICES: "0"
FLASK_APP: server
