name: doc-retriever
endpoints:
  - respond
compose:
  env_file:
    - .env
  build:
    args:
      SERVICE_PORT: 8163
      SERVICE_NAME: doc_retriever
      CONFIG_PATH: ./doc_retriever_config.json
      ORIGINAL_FILE_PATH: ./documents/big_apple.txt
      CUDA_VISIBLE_DEVICES: "0"
      FLASK_APP: server
    context: ./annotators/doc_retriever/
  command: flask run -h 0.0.0.0 -p 8163
  environment:
    - CUDA_VISIBLE_DEVICES=0
    - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 3.5G
      reservations:
        memory: 3.5G
  volumes:
    - "./annotators/doc_retriever:/src"
    - "./common:/src/common"
  ports:
    - 8163:8163
proxy:
  command:
    - nginx
    - -g
    - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
    - PROXY_PASS=dream.deeppavlov.ai:8163
    - PORT=8163
