name: embodied-sender
endpoints:
- send
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8042
      SERVICE_NAME: embodied_sender
      CUDA_VISIBLE_DEVICES: '0'
    context: .
    dockerfile: ./services/embodied_sender/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8042 --timeout 600
  environment:
  - CUDA_VISIBLE_DEVICES=0
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
  volumes:
  - ./common:/src/common
  - ./services/embodied_sender:/src
  ports:
  - 8042:8042