compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8104
      SERVICE_NAME: dff_funfact_skill
    context: .
    dockerfile: ./skills/dff_funfact_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8104
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 256M
compose_dev:
  volumes:
  - ./skills/dff_funfact_skill:/src
  - ./common:/src/common
  ports:
  - 8104:8104
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8104
  - PORT=8104
