compose_override:
  env_file:
  - .env_ru
  build:
    args:
      SERVICE_PORT: 8008
      SERVICE_NAME: dff_program_y_skill
      LANGUAGE: RU
    context: .
    dockerfile: ./skills/dff_program_y_skill/Dockerfile
  command: gunicorn --workers=1 server:app -b 0.0.0.0:8008 --reload
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 128M
compose_dev:
  volumes:
  - ./skills/dff_program_y_skill:/src
  - ./common:/src/common
  ports:
  - 8008:8008
compose_proxy: {}
