convers-evaluation-no-scripts-selector:
- group: response_selectors
  connector:
    protocol: http
    timeout: 1.0
    url: http://convers-evaluation-no-scripts-selector:8009/respond
  dialog_formatter: state_formatters.dp_formatters:full_history_dialog
  response_formatter: state_formatters.dp_formatters:base_response_selector_formatter_service
  previous_services:
  - candidate_annotators
  state_manager_method: add_bot_utterance
  host: convers-evaluation-no-scripts-selector
  port: 8009
  endpoint: respond
scripts-priority-selector:
- group: response_selectors
  connector:
    protocol: http
    timeout: 1.0
    url: http://scripts-priority-selector:8009/respond
  dialog_formatter: state_formatters.dp_formatters:full_history_dialog
  response_formatter: state_formatters.dp_formatters:base_response_selector_formatter_service
  previous_services:
  - candidate_annotators
  state_manager_method: add_bot_utterance
  host: scripts-priority-selector
  port: 8009
  endpoint: respond
convers-evaluation-selector:
- group: response_selectors
  connector:
    protocol: http
    timeout: 1.0
    url: http://convers-evaluation-selector:8009/respond
  dialog_formatter: state_formatters.dp_formatters:full_history_dialog
  response_formatter: state_formatters.dp_formatters:base_response_selector_formatter_service
  previous_services:
  - candidate_annotators
  state_manager_method: add_bot_utterance
  host: convers-evaluation-selector
  port: 8009
  endpoint: respond
convers-evaluation-selector-ru:
- group: response_selectors
  connector:
    protocol: http
    timeout: 1.0
    url: http://convers-evaluation-selector-ru:8009/respond
  dialog_formatter: state_formatters.dp_formatters:full_history_dialog
  response_formatter: state_formatters.dp_formatters:base_response_selector_formatter_service
  previous_services:
  - candidate_annotators
  state_manager_method: add_bot_utterance
  host: convers-evaluation-selector-ru
  port: 8009
  endpoint: respond
no-restrictions-selector:
- group: response_selectors
  connector:
    protocol: http
    timeout: 1.0
    url: http://no-restrictions-selector:8009/respond
  dialog_formatter: state_formatters.dp_formatters:full_history_dialog
  response_formatter: state_formatters.dp_formatters:base_response_selector_formatter_service
  previous_services:
  - candidate_annotators
  state_manager_method: add_bot_utterance
  host: no-restrictions-selector
  port: 8009
  endpoint: respond
