compose_override:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8114
      SERVICE_NAME: user_persona_extractor
    context: .
    dockerfile: ./annotators/user_persona_extractor/Dockerfile
  command: flask run -h 0.0.0.0 -p 8114
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 100M
      reservations:
        memory: 100M
compose_dev:
  volumes:
  - ./annotators/user_persona_extractor:/src
  - ./common:/src/common
  ports:
  - 8114:8114
compose_proxy:
  command:
  - nginx
  - -g
  - daemon off;
  build:
    context: dp/proxy/
    dockerfile: Dockerfile
  environment:
  - PROXY_PASS=dream.deeppavlov.ai:8114
  - PORT=8114
