# С такими volumes удобно дебажить, не нужно пересобирать контейнер каждый раз при изменении кода
services:
  agent:
    volumes:
      - ".:/dp-agent"
    ports:
      - 4242:4242
  sentseg:
    volumes:
      - "./annotators/SentSeg:/src"
    ports:
      - 8011:8011
  convers-evaluation-no-scripts-selector:
    volumes:
      - "./response_selectors/convers_evaluation_based_selector:/src"
      - "./common:/src/common"
    ports:
      - 8009:8009
  badlisted-words:
    volumes:
      - "./annotators/BadlistedWordsDetector:/src"
      - "./common:/src/common"
    ports:
      - 8018:8018
  mongo:
    ports:
      - 27017:27017
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  spelling-preprocessing:
    volumes:
      - "./annotators/spelling_preprocessing:/src"
    ports:
      - 8074:8074
  combined-classification:
    volumes:
      - "./common:/src/common"
      - "./annotators/combined_classification:/src"
      - "~/.deeppavlov:/root/.deeppavlov"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8087:8087
  sentence-ranker:
    volumes:
      - "./services/sentence_ranker:/src"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8128:8128
  transformers-lm-gptj:
    volumes:
      - "./services/transformers_lm:/src"
      - "./common:/src/common"
      - "~/.deeppavlov/cache:/root/.cache"
    ports:
      - 8130:8130
  dff-api-skill:
    volumes:
      - "./skills/dff_api_skill:/src"
      - "./common:/src/common"
      - "./skills/dff_weather_skill/tools:/src/tools"
      - "./skills/dff_weather_skill/data:/src/data"
    ports:
      - 8157:8157
version: "3.7"
